# Generated by Django 5.0.9 on 2026-08-10 13:40

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name_arabic', models.CharField(blank=True, max_length=255, null=True)),
                ('name_english', models.CharField(max_length=255)),
                ('provider', models.CharField(choices=[('SALLA', 'Salla'), ('SHOPIFY', 'Shopify'), ('MAGENTO', 'Magento'), ('ZID', 'Zid'), ('WOOCOMMERCE', 'WooCommerce'), ('OTHER', 'Other')], default='OTHER', max_length=255)),
                ('prefered_store_name', models.CharField(blank=True, max_length=255, null=True)),
                ('countries', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), blank=True, default=list, size=None)),
                ('active_status', models.BooleanField(default=True)),
                ('salla_merchant_id', models.IntegerField(blank=True, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ('name_english',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name_arabic', models.CharField(max_length=500)),
                ('name_english', models.CharField(max_length=500)),
                ('pinecone_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_unit', models.CharField(max_length=255)),
                ('image_url', models.URLField(max_length=2048)),
                ('product_url', models.URLField(max_length=2048)),
                ('category', models.CharField(blank=True, choices=[('chair', 'Chair'), ('2-seater-sofa', '2 Seater Sofa'), ('3-seater-sofa', '3 Seater Sofa'), ('l-shape-sofa', 'L Shape Sofa'), ('sofa', 'Sofa'), ('bed', 'Bed'), ('bedspread', 'Bedspread'), ('pillow', 'Pillow'), ('mattresses', 'Mattresses'), ('mattress-pad', 'Mattress Pad'), ('service-table', 'Service Table'), ('center-table', 'Center Table'), ('side-table', 'Side Table'), ('console', 'Console'), ('dressing-table', 'Dressing Table'), ('comforter', 'Comforter'), ('tv-table', 'Tv Table'), ('dining-table', 'Dining Table'), ('storage-box', 'Storage Box'), ('carpet', 'Carpet'), ('flower-pot-and-plant', 'Flower Pot And Plant'), ('statue-and-antique', 'Statue And Antique'), ('laundry-basket', 'Laundry Basket'), ('candle', 'Candle'), ('candlestick', 'Candlestick'), ('vase', 'Vase'), ('flower', 'Flower'), ('wall-clock', 'Wall Clock'), ('shelve', 'Shelve'), ('decorative-hanger', 'Decorative Hanger'), ('lighting', 'Lighting'), ('lampshade', 'Lampshade'), ('floor-stand', 'Floor Stand'), ('wall-lighting', 'Wall Lighting'), ('outdoor-lighting', 'Outdoor Lighting'), ('chandelier', 'Chandelier'), ('pendant-lighting', 'Pendant Lighting'), ('coffee-maker', 'Coffee Maker'), ('cooking-appliance', 'Cooking Appliance'), ('food-processor', 'Food Processor'), ('cooking-pot', 'Cooking Pot'), ('serving-utensil-and-tray', 'Serving Utensil And Tray'), ('cup', 'Cup'), ('plate', 'Plate'), ('chaise-lounge', 'Chaise Lounge'), ('art-canvas', 'Art Canvas'), ('office-table', 'Office Table'), ('office-chair', 'Office Chair'), ('wardrobe', 'Wardrobe'), ('weight-bench-flat', 'Weight Bench Flat'), ('weight-bench-adjustable', 'Weight Bench Adjustable'), ('stationary-bike', 'Stationary Bike'), ('treadmill', 'Treadmill'), ('dumbbell', 'Dumbbell'), ('elliptical-machine', 'Elliptical Machine'), ('kettlebells', 'Kettlebells'), ('medicine-ball', 'Medicine Ball'), ('power-rack', 'Power Rack'), ('yoga-mat', 'Yoga Mat'), ('leg press machine', 'Leg Press Machine'), ('chest press machine', 'Chest Press Machine'), ('jump rope', 'Jump Rope'), ('air bike', 'Air Bike'), ('barbell', 'Barbell'), ('boxing gloves', 'Boxing Gloves'), ('weight plates', 'Weight Plates')], max_length=255, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, help_text="Along-wall width, per the layout engine's convention.", max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, help_text="Into-room depth, per the layout engine's convention.", max_digits=10, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dimension_unit', models.CharField(blank=True, help_text='cm, in, ft — mixed in live data.', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('detection', models.BooleanField(default=None, null=True)),
                ('product_color', models.CharField(blank=True, help_text='Legacy hex. Still decoded into a palette family for rows with no named main_color.', max_length=50, null=True)),
                ('main_color', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_colors', models.CharField(blank=True, help_text='Comma-separated, as in core_product.', max_length=100, null=True)),
                ('styles', models.CharField(blank=True, help_text='Comma-separated, as in core_product.', max_length=100, null=True)),
                ('room_types', models.CharField(blank=True, max_length=100, null=True)),
                ('style_tags', models.CharField(blank=True, max_length=100, null=True)),
                ('two_d_icon', models.CharField(blank=True, help_text='S3 key, not a URL.', max_length=2048, null=True)),
                ('three_d_model', models.CharField(blank=True, max_length=2048, null=True)),
                ('salla_product_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_updated', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('category_status', models.CharField(choices=[('PENDING', 'Pending review'), ('IN_REVIEW', 'In review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed'), ('GRANDFATHERED', 'Grandfathered (unreviewed)')], db_index=True, default='PENDING', max_length=16)),
                ('dimensions_status', models.CharField(choices=[('PENDING', 'Pending review'), ('IN_REVIEW', 'In review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed'), ('GRANDFATHERED', 'Grandfathered (unreviewed)')], db_index=True, default='PENDING', max_length=16)),
                ('ingestion_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('detection_confidence', models.FloatField(blank=True, null=True)),
                ('detection_model', models.CharField(blank=True, default='', max_length=100)),
                ('bbox', models.JSONField(blank=True, help_text='Detected box, so a re-crop needs no second GPU call.', null=True)),
                ('icon_2d_status', models.CharField(choices=[('PENDING', 'Pending review'), ('IN_REVIEW', 'In review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed'), ('GRANDFATHERED', 'Grandfathered (unreviewed)')], default='PENDING', max_length=16)),
                ('icon_2d_attempts', models.PositiveIntegerField(default=0)),
                ('icon_2d_model', models.CharField(blank=True, default='', max_length=100)),
                ('icon_2d_prompt_version', models.CharField(blank=True, default='', max_length=32)),
                ('metadata_attempts', models.PositiveIntegerField(default=0)),
                ('metadata_issues', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, size=None)),
                ('metadata_model', models.CharField(blank=True, default='', max_length=100)),
                ('model_3d_status', models.CharField(choices=[('PENDING', 'Pending review'), ('IN_REVIEW', 'In review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed'), ('GRANDFATHERED', 'Grandfathered (unreviewed)')], default='PENDING', max_length=16)),
                ('model_3d_attempts', models.PositiveIntegerField(default=0)),
                ('final_3d_generator', models.CharField(blank=True, default='', max_length=32)),
                ('source_image_hash', models.CharField(blank=True, db_index=True, default='', help_text='Detects a merchant changing the image behind a stable URL.', max_length=64)),
                ('import_batch', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pipeline.store')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('category', 'Category'), ('dimensions', 'Dimensions'), ('icon_2d', '2D icon'), ('metadata', 'Metadata'), ('model_3d', '3D model')], max_length=16)),
                ('decision', models.CharField(choices=[('PENDING', 'Pending review'), ('IN_REVIEW', 'In review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed'), ('GRANDFATHERED', 'Grandfathered (unreviewed)')], max_length=16)),
                ('note', models.TextField(blank=True, default='', help_text='Free-text reason. No predefined codes: with no\n                                       regeneration loop there is nothing to map them to.')),
                ('attempt_no', models.PositiveIntegerField(default=0)),
                ('previous_value', models.JSONField(blank=True, help_text='What the reviewer changed, if anything.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_events', to='pipeline.product')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['product', 'artifact_type', '-created_at'], name='idx_event_lookup')],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category_status', 'ingestion_status'], name='idx_stage_ingest'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category_status', 'icon_2d_status'], name='idx_stage_icon'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category_status', 'metadata_attempts'], name='idx_stage_meta'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category_status', 'model_3d_status'], name='idx_stage_3d'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category_status', 'time_created'], name='idx_q_category'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['dimensions_status', 'time_created'], name='idx_q_dimensions'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['icon_2d_status', 'time_updated'], name='idx_q_icon'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('salla_product_id__isnull', False)), fields=('store', 'salla_product_id'), name='uniq_store_salla_product_id'),
        ),
    ]
