# Generated by Django 5.0.9 on 2026-08-11 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_importbatch'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='idx_stage_meta',
        ),
        migrations.RemoveField(
            model_name='product',
            name='bbox',
        ),
        migrations.RemoveField(
            model_name='product',
            name='detection_confidence',
        ),
        migrations.RemoveField(
            model_name='product',
            name='detection_model',
        ),
        migrations.RemoveField(
            model_name='product',
            name='final_3d_generator',
        ),
        migrations.RemoveField(
            model_name='product',
            name='icon_2d_attempts',
        ),
        migrations.RemoveField(
            model_name='product',
            name='icon_2d_model',
        ),
        migrations.RemoveField(
            model_name='product',
            name='icon_2d_prompt_version',
        ),
        migrations.RemoveField(
            model_name='product',
            name='import_batch',
        ),
        migrations.RemoveField(
            model_name='product',
            name='metadata_attempts',
        ),
        migrations.RemoveField(
            model_name='product',
            name='metadata_issues',
        ),
        migrations.RemoveField(
            model_name='product',
            name='metadata_model',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model_3d_attempts',
        ),
        migrations.RemoveField(
            model_name='product',
            name='source_image_hash',
        ),
    ]
