# Generated by Django 5.0.9 on 2026-08-11 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_remove_product_idx_stage_meta_remove_product_bbox_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='product_files/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('file_status', models.IntegerField(choices=[(1, 'pending'), (2, 'processing'), (3, 'failed'), (4, 'completed')], default=1)),
                ('logs', models.JSONField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_files', to='pipeline.store')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='file',
            field=models.ForeignKey(blank=True, help_text='The uploaded sheet this row came from.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='pipeline.productfile'),
        ),
        migrations.DeleteModel(
            name='ImportBatch',
        ),
    ]
