# Generated by Django 5.0.9 on 2026-08-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0004_productfile_product_file_delete_importbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_min_dimension',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviewevent',
            name='artifact_type',
            field=models.CharField(choices=[('category', 'Category'), ('dimensions', 'Dimensions'), ('ingestion', 'Ingestion'), ('icon_2d', '2D icon'), ('metadata', 'Metadata'), ('model_3d', '3D model')], max_length=16),
        ),
    ]
