# Generated by Django 5.0.9 on 2026-08-12 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0005_product_image_min_dimension_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('category', 'Category'), ('dimensions', 'Dimensions'), ('ingestion', 'Ingestion'), ('icon_2d', '2D icon'), ('metadata', 'Metadata'), ('model_3d', '3D model')], help_text='Which artifact changed.', max_length=32)),
                ('status', models.CharField(help_text='What it changed to.', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox_events', to='pipeline.product')),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'indexes': [models.Index(condition=models.Q(('published_at__isnull', True)), fields=['created_at'], name='idx_outbox_unpublished')],
            },
        ),
    ]
