# Generated by Django 5.0.9 on 2026-08-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0006_outboxevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_status',
            field=models.CharField(choices=[('PENDING', 'Pending review'), ('IN_REVIEW', 'In review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed'), ('NOT_APPLICABLE', 'Not applicable'), ('GRANDFATHERED', 'Grandfathered (unreviewed)')], db_index=True, default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimensions_status',
            field=models.CharField(choices=[('PENDING', 'Pending review'), ('IN_REVIEW', 'In review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed'), ('NOT_APPLICABLE', 'Not applicable'), ('GRANDFATHERED', 'Grandfathered (unreviewed)')], db_index=True, default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='icon_2d_status',
            field=models.CharField(choices=[('PENDING', 'Pending review'), ('IN_REVIEW', 'In review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed'), ('NOT_APPLICABLE', 'Not applicable'), ('GRANDFATHERED', 'Grandfathered (unreviewed)')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_3d_status',
            field=models.CharField(choices=[('PENDING', 'Pending review'), ('IN_REVIEW', 'In review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed'), ('NOT_APPLICABLE', 'Not applicable'), ('GRANDFATHERED', 'Grandfathered (unreviewed)')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='reviewevent',
            name='decision',
            field=models.CharField(choices=[('PENDING', 'Pending review'), ('IN_REVIEW', 'In review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed'), ('NOT_APPLICABLE', 'Not applicable'), ('GRANDFATHERED', 'Grandfathered (unreviewed)')], max_length=16),
        ),
    ]
