# Generated by Django 5.0.9 on 2026-08-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0007_alter_product_category_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='metadata_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=16),
        ),
    ]
