# Generated by Django 5.0.9 on 2026-08-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0008_product_metadata_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category_status', 'metadata_status'], name='idx_stage_metadata'),
        ),
    ]
