# Generated by Django 5.0.9 on 2026-08-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0009_product_idx_stage_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ingestion_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('NOT_APPLICABLE', 'Not applicable')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='metadata_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('NOT_APPLICABLE', 'Not applicable')], default='PENDING', max_length=16),
        ),
    ]
