# Generated by Django 5.0.9 on 2026-08-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0010_alter_product_ingestion_status_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='idx_stage_icon',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='idx_stage_metadata',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category_status', 'dimensions_status', 'icon_2d_status'], name='idx_stage_icon'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category_status', 'dimensions_status', 'metadata_status'], name='idx_stage_metadata'),
        ),
    ]
